### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by HaxorGaruda** [reysam93/GNURadio#1]
how to use this tutorial ? i already install and in GRC this block has been added on list....

**Comment by reysam93** [comment]
Hello,
This is not actually a tutorial, I will change the name. This is more a library and a set of exercise for using adaptive OFDM with GNU Radio.
 The files inside Tutorial folder are example I have done following oficial GNU radio tutorials, which you can find [here](http://gnuradio.org/redmine/projects/gnuradio/wiki/Guided_Tutorials). This is a guided tutorial about GNU Radio.
For the other modules, they are based on [this module](https://github.com/bastibl/gr-ieee802-11), so you will need to follow its instructions for using it.
Pay attention to its instructions, as you probably will need to install some dependencies and another module (referred there), and once you install it you need to execute the OFDM PHY file (also explained there).
